language: julia
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'using Pkg, Coverage, QRUpdate; cd(joinpath(dirname(pathof(QRUpdate)), "..")); Codecov.submit(process_folder())'