name = "QRUpdate"
uuid = "37e30a80-ed6e-11e8-2f49-0bf1e58a9240"
authors = ["Harmen Stoppels <harmenstoppels@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
